### PR TITLE
Feature equipment model

### PR DESCRIPTION
**Pull request by TeyimPila**
requesting to merge the feature equipment model into feature add model #1

### CODE REVIEW

**Comment by skaex** [comment]
Approved. For now

[Approved with PullApprove](https://pullapprove.com/TeyimPila/tela-mis/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=TeyimPila/tela-mis)

**Comment by TeyimPila** [comment]
Hello SkaeX,
Are you going to merged the approved PRs or we are to do that?





Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=teyim.pila@aun.edu.ng&idSignature=22>

On Sun, Mar 13, 2016 at 4:46 PM, SkaeX <notifications@github.com> wrote:

> Approved. For now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeyimPila/tela-mis/pull/15#issuecomment-195982140>.
>



-- 
*Teyim M. Pila*
*Computer Science Major*
*School Of Information Technology and computing*
*American University of Nigeria <http://www.americanuniversitynigeria.org>
Yola, Adamawa state*
*+2348166180681 (Nig.)*
*+237673193376 (Cam.)*

**Comment by SkaeX** [comment]
I will. Just resolving some conflicts.

**Comment by TeyimPila** [comment]
ok Thanks



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=teyim.pila@aun.edu.ng&idSignature=22>

On Sun, Mar 13, 2016 at 4:50 PM, SkaeX <notifications@github.com> wrote:

> I will. Just resolving some conflicts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeyimPila/tela-mis/pull/15#issuecomment-195982607>.
>



-- 
*Teyim M. Pila*
*Computer Science Major*
*School Of Information Technology and computing*
*American University of Nigeria <http://www.americanuniversitynigeria.org>
Yola, Adamawa state*
*+2348166180681 (Nig.)*
*+237673193376 (Cam.)*

**Comment by TeyimPila** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/c3e6bb398b",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Teyim is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    
If you would like to unsubscribe and stop receiving these emails click here.

**Pull request merged**
